### ISSUE TITLE
COO Cook Droid not working

### ISSUE THREAD

**Issue by Smidgehaydn** [FantasyFanGitHub/Rimworld-Star-Wars---Droids#2]
COO Cook Droid appears red on the build tab for some reason,
I've built it but theres no way to load it with the items needed, I've tried leaving items in the spots and tried using people to load it but no luck

**Comment by FantasyFanGitHub** [comment]
The droid uses hoppers like the paste dispenser and it's completly red because in the build tab you can't use texture masks

**Comment by Smidgehaydn** [comment]
Oo thankyou! No errors or issues with biotech yet, I'm guessing to make droids I need to research the vanilla faction expanded mod? As don't see a droid tab

**Comment by FantasyFanGitHub** [comment]
When 'Biotech' is active you have to research Basic/... mechtech and you have to gestate them. In the next update I plan to add mod options to switch between 'biotech' mechanoids and 'vfe mechanoid' versions when starting a new save.
